// <auto-generated />
using DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(db_prizebond_DBContext))]
    [Migration("20250928120843_experi2")]
    partial class experi2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BOL.Entities.BondOwned", b =>
                {
                    b.Property<int>("ObId_2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ob_id_2");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObId_2"));

                    b.Property<int>("ObBondNo")
                        .HasColumnType("int")
                        .HasColumnName("ob_bond_no");

                    b.Property<string>("ObBondSeries")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("ob_bond_series");

                    b.HasKey("ObId_2");

                    b.ToTable("bond_owned");
                });

            modelBuilder.Entity("BOL.Entities.BondWinning", b =>
                {
                    b.Property<int>("WbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wb_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WbId"));

                    b.Property<int?>("WbBondNo")
                        .HasColumnType("int")
                        .HasColumnName("wb_bond_no");

                    b.Property<string>("WbDrawName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("wb_draw_name");

                    b.Property<int?>("WbEntrySl")
                        .HasColumnType("int")
                        .HasColumnName("wb_entry_sl");

                    b.Property<int?>("WbWinPlace")
                        .HasColumnType("int")
                        .HasColumnName("wb_win_place");

                    b.HasKey("WbId");

                    b.ToTable("bond_winning");
                });
#pragma warning restore 612, 618
        }
    }
}
